Repository SCIInstitute/Seg3D, pull requests merged in 2020-07, with the labels that each got.

#350 Update Qt version
  Superbuild/Superbuild.cmake
Labels: Qt5

#357 Removed ITKDataLayerExporter warnings
  src/Application/LayerIO/ITKDataLayerExporter.cc
Labels: build

#358 Update OSX minimum version
  Superbuild/Superbuild.cmake
Labels: build

#355 GitHub action builds
  .github/workflows/linux.yml
  .github/workflows/mac.yml
  .github/workflows/windows.yml
Labels: build

#347 Fix for layer manager visibility stylesheet
  src/Interface/Application/LayerManagerWidget.cc
  src/Interface/Application/StyleSheet.cc
  src/Interface/Application/StyleSheet.h
Labels: GUI

#360 Update minor and patch version
  .github/workflows/mac.yml
  .github/workflows/windows.yml
  src/CMakeLists.txt
Labels: build
